### ISSUE TITLE
crash server 

### ISSUE THREAD

**Issue by ezekutor** [Stimayk/ServerInfo-for-LR-WEB#1]
```
16:17:35.886] CSSharp: Native 5df2e20d was invoked on a non-main thread
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '17' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ServerInfo.ServerInfo.UpdatePlayerInfoAsync()
   at ServerInfo.ServerInfo.<OnRoundStart>b__59_1()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Using breakpad crash handler
```

**Comment by xeeek** [comment]
Проблема сохраняется
